import ThemeContextProvider from "@/context/theme-context";
import StyledComponentsRegistry from "../../lib/registry";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ko">
      <body>
        <ThemeContextProvider>
          <StyledComponentsRegistry>{children}</StyledComponentsRegistry>
        </ThemeContextProvider>
      </body>
    </html>
  );
}
